apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: s25j3jtme-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/s25j3jtme-java-springboot-gitops